### ISSUE TITLE
Chapter 5 - ComputeMesh (sample 9) exceeds maxComputeWorkGroupCount

### ISSUE THREAD

**Issue by sjfricke** [PacktPublishing/3D-Graphics-Rendering-Cookbook-Second-Edition#4]
running on Intel Mesa, my `maxComputeWorkGroupCount[0]` is only 64k and I am getting VVL errors as the dispatch group is too large (confirmed with debugger it is setting `524288`)

>  Validation Error: VUID-vkCmdDispatch-groupCountX-00386  
 vkCmdDispatch(): groupCountX (524288) exceeds device limit maxComputeWorkGroupCount[0] (65535).

**Comment by corporateshark** [comment]
Fixed in 0e74afa724b4bd8b81dd550cea498df035e3c249
