### ISSUE TITLE
Issues with large scenes in Chapter 7 with Nvidia RTX 4080 

### ISSUE THREAD

**Issue by alfonsmagd** [PacktPublishing/3D-Graphics-Rendering-Cookbook-Second-Edition#6]
![artifact sample 7 , large scene](https://github.com/user-attachments/assets/e5894022-363e-40b5-9d46-b9a10035f6cf)
![image](https://github.com/user-attachments/assets/488fee5c-b8a8-4d0f-9763-a47594b64645)
Validation Layers not report error.  I ran it in Release mode, and I haven’t modified anything; I just wanted to test it. The same thing happens in chapter 10 where the scene is used, and the framerate is very low. I will update the drivers. Regards.

**Comment by corporateshark** [comment]
This is a known issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8579

Please update to the Vulkan SDK 1.3.296 or disable this validation option in Vulkan Configurator: ` GPU-Assisted - Buffer content validation - Indirect draw parameters`

**Comment by alfonsmagd** [comment]
Thanks, updating the SDK to version 1.3.296 solved the problem. I haven't debugged much, but I kept encountering this error (running the same proyect).  which didn't show up with version 1.3.289. I’m sharing the validation layers in case it might be of interest: Validation layer:


 Validation Error: UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout
 Object 0: handle = 000002843365F050, type = VK_OBJECT_TYPE_COMMAND_BUFFER;
 MessageID = 0000000000000000
 vkCmdDraw():  command buffer VkCommandBuffer 0x2843365f050[] expects VkImage 0xdf979d00000006c5[Image: .cache/out_textures/deps__src__bistro__interior______othertextures__tiling__metal_chrome_01__metal_chrome_01_diff.png__rescaled.ktx] (subresource: aspectMask VK_IMAGE_ASPECT_COLOR_BIT array layer 0, mip level 8) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.

ERROR:
Validation layer:
 Validation Error: UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout
 Object 0: handle = 000002843365F050, type = VK_OBJECT_TYPE_COMMAND_BUFFER;
 MessageID = 0000000000000000
 vkCmdDraw():  command buffer VkCommandBuffer 0x2843365f050[] expects VkImage 0xdf979d00000006c5[Image: .cache/out_textures/deps__src__bistro__interior______othertextures__tiling__metal_chrome_01__metal_chrome_01_diff.png__rescaled.ktx] (subresource: aspectMask VK_IMAGE_ASPECT_COLOR_BIT array layer 0, mip level 9) to be in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED. 

![image](https://github.com/user-attachments/assets/7e6ffeba-5a49-4848-8bd5-b159d804ca27)

**Comment by corporateshark** [comment]
@alfonsmagd I think this is another false-positive issue in the Validation Layers.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8688

**Comment by alfonsmagd** [comment]
Thank you very much for your response, and counting the days for the new book release.
